name: hdnet-standard
services:
  appservice:
    type: php:8.0
    via: cli
    xdebug: 'debug,develop'
    composer_version: '2.1.9'
    run:
      - composer install
    config:
      php: config/lando/php/php.ini
tooling:
  composer:
    service: appservice
  xdebug-on-request:
    service: appservice
    description: Start xdebug with request
    cmd: sed -i 's/xdebug.start_with_request=no/xdebug.start_with_request=yes/g' /app/.lando/config/php/php.ini
  xdebug-off-request:
    service: appservice
    description: Do not start xdebug with request
    cmd: sed -i 's/xdebug.start_with_request=yes/xdebug.start_with_request=no/g' /app/.lando/config/php/php.ini
